from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
from flask_login import login_required, current_user
from models import db, User, Proposal, ApprovalStep, DocumentApproval, ProposalMessage
from utils import add_signature_page_bytes, build_proposal_pdf_bytes
from utils import build_month_matrix, get_proposal_venue, normalize_proposal_data, parse_event_date, proposal_needs_budget
from datetime import datetime, date
import calendar
from sqlalchemy.orm.attributes import flag_modified
from storage import storage

office_bp = Blueprint('office', __name__)

ORG_DEPARTMENTS = {
    'icons': 'Computer Science Dept',
    'hibe': 'Biology Dept',
    'psych': 'Psychology Dept',
    'kwago': 'Political Science Dept',
    'aces': 'Communication and English Studies',
    'casso': 'CAS',
}

def _get_printed_name(user):
    profile = user.profile_data or {}
    return (profile.get('printed_name') or '').strip()


def _office_step_for_user(user):
    return ApprovalStep.query.filter(ApprovalStep.name.ilike(user.username)).first()


def _conversation_messages(proposal_id, office_step_id):
    return ProposalMessage.query.filter_by(
        proposal_id=proposal_id,
        office_step_id=office_step_id,
    ).order_by(ProposalMessage.created_at.asc()).all()


def _office_dashboard_items(step_id):
    active_proposals = Proposal.query.filter_by(current_step_id=step_id).order_by(Proposal.created_at.desc()).all()
    active_ids = {proposal.id for proposal in active_proposals}

    message_rows = ProposalMessage.query.filter_by(office_step_id=step_id).order_by(ProposalMessage.created_at.desc()).all()
    followup_ids = []
    seen_ids = set()
    for message in message_rows:
        if message.proposal_id in active_ids or message.proposal_id in seen_ids:
            continue
        followup_ids.append(message.proposal_id)
        seen_ids.add(message.proposal_id)

    followup_proposals = []
    if followup_ids:
        proposals_by_id = {
            proposal.id: proposal
            for proposal in Proposal.query.filter(Proposal.id.in_(followup_ids)).all()
        }
        followup_proposals = [
            proposals_by_id[proposal_id]
            for proposal_id in followup_ids
            if proposal_id in proposals_by_id
        ]

    dashboard_items = [{'proposal': proposal, 'mode': 'review'} for proposal in active_proposals]
    dashboard_items.extend({'proposal': proposal, 'mode': 'chat'} for proposal in followup_proposals)
    return dashboard_items


def _filter_dashboard_items(dashboard_items, search='', username_filter='', mode_filter=''):
    normalized_search = (search or '').strip().lower()
    normalized_user = (username_filter or '').strip().lower()
    normalized_mode = (mode_filter or '').strip().lower()

    filtered_items = []
    for item in dashboard_items:
        proposal = item['proposal']
        creator_name = (proposal.creator.username if proposal.creator else '').strip()
        title = (proposal.title or '').strip()

        if normalized_search and normalized_search not in title.lower():
            continue
        if normalized_user and creator_name.lower() != normalized_user:
            continue
        if normalized_mode and item['mode'] != normalized_mode:
            continue

        filtered_items.append(item)

    return filtered_items


def _next_pending_step(proposal, current_order):
    remaining_steps = ApprovalStep.query.filter(
        ApprovalStep.step_order > current_order
    ).order_by(ApprovalStep.step_order.asc()).all()
    approvals_by_step = {approval.step_id: approval for approval in proposal.approvals}

    for step in remaining_steps:
        if step.name.strip().upper() == 'FINANCE' and not proposal_needs_budget(proposal.proposal_data):
            continue
        approval = approvals_by_step.get(step.id)
        if not approval or approval.status != 'approved':
            return step

    return None


def _signed_roles_for_pdf(proposal, current_step_name=None, current_printed_name=None):
    signed_roles = {}

    for approval in proposal.approvals:
        if not approval.step or approval.status != 'approved' or not approval.signed_name:
            continue
        signed_roles[approval.step.name.upper()] = approval.signed_name

    if current_step_name and current_printed_name:
        signed_roles[current_step_name.upper()] = current_printed_name

    return signed_roles


def _should_use_generated_preview(file_path):
    if not file_path:
        return True

    try:
        pdf_bytes = storage.read_bytes(file_path)
    except Exception:
        return True

    # Full proposal PDFs generated by the app are typically hundreds of KB
    # because they include the proposal body and branding assets. Tiny files
    # in the low-KB range are usually the signature-only outputs from an
    # overwritten collision and should fall back to the reconstructed preview.
    return len(pdf_bytes) < 20_000


def _approved_calendar_events():
    events = []
    proposals = Proposal.query.filter_by(status='APPROVED').order_by(Proposal.created_at.desc()).all()
    for proposal in proposals:
        proposal_data = normalize_proposal_data(proposal.proposal_data)
        event_date = parse_event_date(proposal_data.get('event_date'))
        if not event_date:
            continue

        events.append({
            'proposal_id': proposal.id,
            'title': proposal.title,
            'org_name': proposal.creator.username if proposal.creator else 'Unknown organization',
            'event_date': event_date,
            'date_label': event_date.strftime('%B %d, %Y'),
            'venue': get_proposal_venue(proposal_data),
        })

    return sorted(events, key=lambda item: (item['event_date'], item['title'].lower()))


def _calendar_month_context(events, year, month):
    month_matrix = build_month_matrix(year, month)
    month_name = calendar.month_name[month]
    today = date.today()
    events_by_day = {}
    monthly_events = []

    for event in events:
        if event['event_date'].year == year and event['event_date'].month == month:
            events_by_day.setdefault(event['event_date'].day, []).append(event)
            monthly_events.append(event)

    for day_events in events_by_day.values():
        day_events.sort(key=lambda item: (item['event_date'], item['title'].lower()))

    prev_year, prev_month = (year - 1, 12) if month == 1 else (year, month - 1)
    next_year, next_month = (year + 1, 1) if month == 12 else (year, month + 1)

    return {
        'month_matrix': month_matrix,
        'events_by_day': events_by_day,
        'monthly_events': sorted(monthly_events, key=lambda item: (item['event_date'], item['title'].lower())),
        'month_name': month_name,
        'today': today,
        'prev_year': prev_year,
        'prev_month': prev_month,
        'next_year': next_year,
        'next_month': next_month,
    }

@office_bp.route('/office-home', methods=['GET', 'POST'])
@office_bp.route('/office-home/<int:review_id>', methods=['GET', 'POST'])
@login_required
def review(review_id=None):
    my_step = _office_step_for_user(current_user)
    
    if not my_step:
        flash("Account not linked to a valid approval step.", "danger")
        return redirect(url_for('auth.signin'))

    if request.method == 'POST' and review_id:
        prop = db.session.get(Proposal, review_id)
        if not prop:
            abort(404)

        action = request.form.get('action')
        remarks = request.form.get('remarks')
        printed_name = (request.form.get('printed_name') or _get_printed_name(current_user)).strip()
  
        current_approval = DocumentApproval.query.filter_by(
            document_id=prop.id, 
            step_id=my_step.id
        ).first()

        if action == 'approve':
            if not printed_name:
                flash("Set your printed name first so it can be used as your digital signature.", "warning")
                return redirect(url_for('office.review', review_id=review_id))

            profile = dict(current_user.profile_data or {})
            profile['printed_name'] = printed_name
            current_user.profile_data = profile
            flag_modified(current_user, 'profile_data')
            db.session.add(current_user)
         
            proposal_data = normalize_proposal_data(prop.proposal_data)
            signed_roles = _signed_roles_for_pdf(
                prop,
                current_step_name=my_step.name,
                current_printed_name=printed_name,
            )
            signed_pdf_bytes = None
            try:
                existing_pdf_bytes = storage.read_bytes(prop.file_path) if prop.file_path else None
            except Exception:
                existing_pdf_bytes = None

            if existing_pdf_bytes:
                signed_pdf_bytes = add_signature_page_bytes(
                    existing_pdf_bytes,
                    signed_roles,
                    proposal_data=proposal_data,
                )

            if not signed_pdf_bytes:
                signed_pdf_bytes = build_proposal_pdf_bytes(
                    proposal_data,
                    signed_roles=signed_roles,
                    title=prop.title,
                )

            if signed_pdf_bytes:
                if prop.file_path:
                    try:
                        storage.write_bytes(prop.file_path, signed_pdf_bytes, content_type='application/pdf')
                    except Exception:
                        pass
                current_approval.signed_name = printed_name
                current_approval.status = 'approved'
                current_approval.remarks = remarks
                current_approval.approved_at = datetime.utcnow()
                current_approval.approved_by = current_user.id

                next_s = _next_pending_step(prop, my_step.step_order)

                if next_s:
                    prop.current_step_id = next_s.id
                else:
                    prop.status = 'APPROVED'
                    prop.current_step_id = None

                flash(f"Proposal '{prop.title}' signed and forwarded.", "success")
            else:
                flash("Failed to generate the signed PDF for this proposal.", "danger")

        elif action == 'reject':

            current_approval.status = 'rejected'
            current_approval.remarks = remarks
            current_approval.approved_at = datetime.utcnow()
            prop.status = 'REJECTED'
   
            prop.current_step_id = None 
            flash(f"Proposal '{prop.title}' has been rejected and returned to the organization.", "warning")

        db.session.commit()
        return redirect(url_for('office.review'))
 
    dashboard_items = _office_dashboard_items(my_step.id)
    search = (request.args.get('search') or '').strip()
    username_filter = (request.args.get('username_filter') or '').strip()
    mode_filter = (request.args.get('mode_filter') or '').strip()
    filtered_dashboard_items = _filter_dashboard_items(
        dashboard_items,
        search=search,
        username_filter=username_filter,
        mode_filter=mode_filter,
    )
    department_options = []
    seen_orgs = set()
    for item in dashboard_items:
        proposal = item['proposal']
        if not proposal.creator:
            continue
        username = proposal.creator.username.strip()
        key = username.lower()
        if key in seen_orgs:
            continue
        seen_orgs.add(key)
        department_options.append({
            'username': username,
            'label': f"{username} - {ORG_DEPARTMENTS.get(key, username)}",
        })
    department_options.sort(key=lambda option: option['label'].lower())
    selected = db.session.get(Proposal, review_id) if review_id else None
    selected_messages = _conversation_messages(selected.id, my_step.id) if selected else []
    active_tab = request.args.get('tab', 'overview')
    if active_tab not in {'overview', 'chat'}:
        active_tab = 'overview'

    proposal_preview_data = normalize_proposal_data(selected.proposal_data) if selected else None
    if proposal_preview_data is not None:
        proposal_preview_data = dict(proposal_preview_data)
        proposal_preview_data['signed_roles'] = _signed_roles_for_pdf(selected)
        proposal_preview_data['title'] = selected.title
    use_generated_preview = _should_use_generated_preview(selected.file_path) if selected else False

    return render_template(
        'office_home.html', 
        dashboard_items=filtered_dashboard_items,
        selected_proposal=selected,
        proposal_preview_data=proposal_preview_data,
        selected_messages=selected_messages,
        active_tab=active_tab,
        username=current_user.username,
        pending_count=len(filtered_dashboard_items),
        printed_name=_get_printed_name(current_user),
        department_options=department_options,
        dashboard_filters={
            'search': search,
            'username_filter': username_filter,
            'mode_filter': mode_filter,
        },
        use_generated_preview=use_generated_preview,
    )

@office_bp.route('/office-profile', methods=['POST'])
@login_required
def update_profile():
    if current_user.account_type != 'Office':
        abort(403)

    printed_name = (request.form.get('printed_name') or '').strip()
    profile = dict(current_user.profile_data or {})
    profile['printed_name'] = printed_name
    current_user.profile_data = profile
    flag_modified(current_user, 'profile_data')
    db.session.add(current_user)
    db.session.commit()

    if printed_name:
        flash("Printed name saved. It will now be used as your digital signature.", "success")
    else:
        flash("Printed name cleared.", "warning")

    return redirect(url_for('office.review'))


@office_bp.route('/proposal-messages/<int:proposal_id>', methods=['POST'])
@login_required
def send_message(proposal_id):
    if current_user.account_type != 'Office':
        abort(403)

    my_step = _office_step_for_user(current_user)
    if not my_step:
        abort(403)

    proposal = db.session.get(Proposal, proposal_id)
    if not proposal:
        abort(404)

    body = (request.form.get('message') or '').strip()
    if not body:
        flash('Message cannot be empty.', 'warning')
    else:
        db.session.add(ProposalMessage(
            proposal_id=proposal.id,
            office_step_id=my_step.id,
            sender_id=current_user.id,
            sender_role=current_user.account_type,
            body=body,
        ))
        db.session.commit()
        flash('Your message was added to the conversation.', 'success')

    return_to = request.form.get('return_to')
    if return_to == 'details':
        return redirect(url_for('office.proposal_details', proposal_id=proposal.id, tab='chat'))
    return redirect(url_for('office.review', review_id=proposal.id, tab='chat'))

# ... existing review function ...

@office_bp.route('/master-history')
@login_required
def master_history():
    """Global history for Office accounts to review all organizations."""
    if current_user.account_type != 'Office':
        abort(403)

    query = Proposal.query.join(User, Proposal.creator_id == User.id).filter(User.account_type == 'Org')

    # Global Search
    search = request.args.get('search')
    if search:
        query = query.filter(Proposal.title.ilike(f'%{search}%'))

    # Filter by specific Organization (Username)
    username_filter = (request.args.get('username_filter') or '').strip()
    if username_filter:
        query = query.filter(User.username.ilike(username_filter))

    # Apply Date Filter
    date_from = request.args.get('date_from')
    if date_from:
        try:
            date_obj = datetime.strptime(date_from, '%Y-%m-%d')
            query = query.filter(Proposal.created_at >= date_obj)
        except ValueError:
            pass 

    proposals = query.order_by(Proposal.created_at.desc()).all()
    
    department_options = [
        {'username': 'Icons', 'label': 'Icons - Computer Science Dept'},
        {'username': 'Hibe', 'label': 'Hibe - Biology Dept'},
        {'username': 'Psych', 'label': 'Psych - Psychology Dept'},
        {'username': 'Kwago', 'label': 'Kwago - Political Science Dept'},
        {'username': 'Aces', 'label': 'Aces - Communication and English Studies'},
        {'username': 'Casso', 'label': 'Casso - CAS'},
    ]

    return render_template(
        'submission_history.html',
        proposals=proposals,
        is_history=True,
        is_office=True,
        department_options=department_options,
        department_map=ORG_DEPARTMENTS
    )


@office_bp.route('/office-calendar')
@login_required
def calendar_view():
    if current_user.account_type != 'Office':
        abort(403)

    today = date.today()
    year = request.args.get('year', type=int) or today.year
    month = request.args.get('month', type=int) or today.month

    if month < 1 or month > 12:
        month = today.month
    if year < 2000 or year > 2100:
        year = today.year

    events = _approved_calendar_events()
    calendar_context = _calendar_month_context(events, year, month)

    return render_template(
        'calendar.html',
        page_title='Calendar of Activities',
        page_subtitle='Browse approved activities across organizations and reviewing offices.',
        account_sub='Office',
        dashboard_endpoint='office.review',
        history_endpoint='office.master_history',
        calendar_endpoint='office.calendar_view',
        review_endpoint='office.review',
        **calendar_context,
    )

@office_bp.route('/proposal-details/<int:proposal_id>')
@login_required
def proposal_details(proposal_id):
    """Detailed PDF viewer for office accounts."""
    if current_user.account_type != 'Office':
        abort(403)

    my_step = _office_step_for_user(current_user)
    if not my_step:
        abort(403)

    proposal = db.session.get(Proposal, proposal_id)
    if not proposal:
        abort(404)

    current_step_name = None
    if proposal.current_step_id:
        current_step = db.session.get(ApprovalStep, proposal.current_step_id)
        current_step_name = current_step.name if current_step else None
    messages = _conversation_messages(proposal.id, my_step.id)
    active_tab = request.args.get('tab', 'overview')
    if active_tab not in {'overview', 'chat'}:
        active_tab = 'overview'

    proposal_preview_data = normalize_proposal_data(proposal.proposal_data)
    proposal_preview_data = dict(proposal_preview_data)
    proposal_preview_data['signed_roles'] = _signed_roles_for_pdf(proposal)
    proposal_preview_data['title'] = proposal.title

    return render_template(
        'office_proposal_detail.html',
        proposal=proposal,
        proposal_preview_data=proposal_preview_data,
        department_name=ORG_DEPARTMENTS.get(proposal.creator.username.lower(), proposal.creator.username),
        current_step_name=current_step_name,
        messages=messages,
        active_tab=active_tab,
        use_generated_preview=_should_use_generated_preview(proposal.file_path),
    )
